### ISSUE TITLE
Uneinheitlicher Cursor für den Dark-Mode- bzw. Light-Mode-Button und Rechtschreibfehler im Readme

### ISSUE THREAD

**Issue by q-Sci** [chefredaktion/berthasecho#1]
Wärend in der Navbar für die Links die CSS-Property `cursor: pointer` (der Zeigefinger-Cursor) gilt, existiert für den Knopf zum Wechsel zwischen dem dunklen und hellen Modus nur die Regel für den normalen Cursor, was eine kleine, aber aufregende Unregelmäßigkeit darstellt.

Zudem fehlt im letzten Absatz des Readmes ein Leerzeichen in der Zeichenfolge `Githubauskennt`.

**Comment by chefredaktion** [comment]
Vielen Dank für die Hinweise. Sind nun korrigiert.
